# Generated by Django 4.1.5 on 2023-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slr_img', models.ImageField(upload_to='stats_img/', verbose_name='Динамика оклада по годам')),
                ('count_vac_img', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по годам')),
                ('table', models.FileField(default=None, upload_to='upload_files/', verbose_name='Таблица динамики оклада и количества вакансий по годам')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slr_img', models.ImageField(upload_to='stats_img/', verbose_name='Динамика оклада по городам')),
                ('count_vac_img', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по городам')),
                ('slr_table', models.FileField(default=None, upload_to='upload_files/', verbose_name='Таблица уровня оклада по городам')),
                ('count_vac_table', models.FileField(default=None, upload_to='upload_files/', verbose_name='Таблица долей вакансий по городам')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='KeySkillsPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('key_skills_img', models.ImageField(upload_to='stats_img/', verbose_name='Топ 10 навыков')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
    ]
