# Generated by Django 4.1.5 on 2023-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpageels',
            name='count_vac_img',
            field=models.ImageField(upload_to='stat_img/', verbose_name='Количество вакансий по годам'),
        ),
        migrations.AlterField(
            model_name='demandpageels',
            name='slr_img',
            field=models.ImageField(upload_to='stat_img/', verbose_name='Динамика оклада по годам'),
        ),
        migrations.AlterField(
            model_name='demandpageels',
            name='table',
            field=models.FileField(default=None, upload_to='CSVs/', verbose_name='Таблица динамики оклада и количества вакансий по годам'),
        ),
        migrations.AlterField(
            model_name='geographypageels',
            name='count_vac_img',
            field=models.ImageField(upload_to='stat_img/', verbose_name='Количество вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='geographypageels',
            name='count_vac_table',
            field=models.FileField(default=None, upload_to='CSVs/', verbose_name='Таблица долей вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='geographypageels',
            name='slr_img',
            field=models.ImageField(upload_to='stat_img/', verbose_name='Динамика оклада по городам'),
        ),
        migrations.AlterField(
            model_name='geographypageels',
            name='slr_table',
            field=models.FileField(default=None, upload_to='CSVs/', verbose_name='Таблица уровня оклада по городам'),
        ),
        migrations.AlterField(
            model_name='keyskillspageels',
            name='key_skills_img',
            field=models.ImageField(upload_to='stat_img/', verbose_name='Топ 10 навыков'),
        ),
    ]
